trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'myACR'
              repository: 'webapi'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'your-azure-subscription'
              azureResourceGroup: 'myResourceGroup'
              kubernetesCluster: 'myAKSCluster'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'k8-deployment.yml'
